version: "3.9"

services:
  database:
    image: postgres
    container_name: database_laudei
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=laudei
      - POSTGRES_PASSWORD=Chikinitos@2021!
      - POSTGRES_DB=laudei
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: laudei
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local